training_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "loss_train" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_min_loss"
  auto_insert_metric_name: False

#early_stopping:
#  _target_: pytorch_lightning.callbacks.EarlyStopping
#  monitor: "precision_at_1/validation/mean"
#  min_delta: 0.005
#  mode: max
#  patience: 10
#  verbose: False
#  strict: False
#  stopping_threshold: 1
#  # divergence_threshold: 0.5
#  check_on_train_epoch_end: False

precision_at_1_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "precision_at_1/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_max_mean_precision_at_1"
  auto_insert_metric_name: False

r_precision_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "r_precision/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_max_r_precision"
  auto_insert_metric_name: False

majority_vote_at_30_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "majority_vote_at_30/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_majority_vote_at_30"
  auto_insert_metric_name: False

majority_vote_at_50_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "majority_vote_at_50/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_majority_vote_at_50"
  auto_insert_metric_name: False

sequence_mrr_at_5_mins_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "sequence_mrr_at_5_mins/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_sequence_mrr_at_5_mins"
  auto_insert_metric_name: False

sequence_mrr_at_10_mins_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "sequence_mrr_at_10_mins/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_sequence_mrr_at_10_mins"
  auto_insert_metric_name: False

sequence_top_1_accuracy_5_mins_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "sequence_top_1_accuracy_5_mins/validation/mean"
  mode: "max"
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_sequence_top_1_accuracy_5_mins"
  auto_insert_metric_name: False